# Generated by Django 5.1.3 on 2024-11-28 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_device_last_used_device_total_usage_time_device_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='total_usage_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
