# Generated by Django 5.0.7 on 2024-12-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_pricingplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
