# Generated by Django 5.0.7 on 2024-12-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_remove_pricingplan_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
